"""
CodeReview — Generated by effector compile --target langchain
Source: effector.toml + SKILL.md
"""

from langchain.tools import BaseTool
from pydantic import BaseModel, Field
from typing import Type, Optional


class CodeReviewInput(BaseModel):
    """Input schema for CodeReview."""
    github_token: str = Field(description="Environment variable: GITHUB_TOKEN")


class CodeReviewTool(BaseTool):
    """Performs automated code review on pull request diffs"""
    name: str = "code_review"
    description: str = "Performs automated code review on pull request diffs"
    args_schema: Type[BaseModel] = CodeReviewInput

    def _run(self, **kwargs) -> str:
        """Execute the skill. Override this method with actual implementation."""
        # Instruction passthrough: return SKILL.md content for the LLM
        return """# Code Review

## Instructions

1. Read the provided code diff
2. Analyze for bugs, style issues, and potential improvements
3. Return a structured ReviewReport with findings

## Examples

**Input**: A diff from a pull request adding a new API endpoint
**Output**: ReviewReport with severity-tagged findings"""

    async def _arun(self, **kwargs) -> str:
        return self._run(**kwargs)
