/**
 * @module @effectorhq/core/compile
 *
 * Cross-runtime compiler targets.
 * Takes parsed effector.toml + SKILL.md and emits runtime-specific tool definitions.
 *
 * Supported targets:
 *   mcp           → MCP tool schema (JSON-RPC 2.0)
 *   openai-agents → OpenAI Agents FunctionTool definition
 *   langchain     → LangChain StructuredTool Python class
 *   json          → Raw effector IR (passthrough)
 */

/**
 * Compile an effector definition to a specific runtime target.
 *
 * @param {Object} effectorDef - Parsed effector definition
 *        { name, version, type, description, interface, permissions, skillContent }
 * @param {string} target - Target runtime: 'mcp' | 'openai-agents' | 'langchain' | 'json'
 * @returns {string} Compiled output as string
 */
export function compile(effectorDef, target = 'json') {
  switch (target) {
    case 'mcp':
      return compileMCP(effectorDef);
    case 'openai-agents':
      return compileOpenAIAgents(effectorDef);
    case 'langchain':
      return compileLangChain(effectorDef);
    case 'json':
      return JSON.stringify(effectorDef, null, 2);
    default:
      throw new Error(`Unknown compile target: "${target}". Supported: mcp, openai-agents, langchain, json`);
  }
}

/**
 * List available compile targets.
 */
export function listTargets() {
  return [
    { name: 'mcp', description: 'MCP tool schema (JSON-RPC 2.0)', format: 'json' },
    { name: 'openai-agents', description: 'OpenAI Agents FunctionTool definition', format: 'json' },
    { name: 'langchain', description: 'LangChain StructuredTool Python class', format: 'python' },
    { name: 'json', description: 'Raw effector IR (passthrough)', format: 'json' },
  ];
}

// ── MCP Target ────────────────────────────────────────────

function compileMCP(def) {
  const name = normalizeName(def.name);
  const envVars = extractEnvVars(def);

  const tool = {
    name,
    description: def.description || 'No description provided',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  };

  for (const envVar of envVars) {
    tool.inputSchema.properties[envVar] = {
      type: 'string',
      description: `Environment variable: ${envVar}`,
    };
  }
  if (envVars.length > 0) {
    tool.inputSchema.required = envVars;
  }

  if (def.interface) {
    tool._interface = {
      input: def.interface.input || null,
      output: def.interface.output || null,
      context: def.interface.context || [],
    };
  }

  return JSON.stringify(tool, null, 2);
}

// ── OpenAI Agents Target ──────────────────────────────────

function compileOpenAIAgents(def) {
  const name = normalizeName(def.name);
  const envVars = extractEnvVars(def);

  // OpenAI Agents SDK FunctionTool format
  const functionDef = {
    type: 'function',
    function: {
      name,
      description: def.description || 'No description provided',
      parameters: {
        type: 'object',
        properties: {},
        required: envVars.length > 0 ? envVars : undefined,
      },
    },
  };

  for (const envVar of envVars) {
    functionDef.function.parameters.properties[envVar] = {
      type: 'string',
      description: `Environment variable: ${envVar}`,
    };
  }

  // Include skill instructions as system context
  if (def.skillContent) {
    functionDef._effector = {
      skillContent: def.skillContent,
      interface: def.interface || null,
    };
  }

  return JSON.stringify(functionDef, null, 2);
}

// ── LangChain Target ──────────────────────────────────────

function compileLangChain(def) {
  const className = toPascalCase(def.name);
  const name = normalizeName(def.name);
  const envVars = extractEnvVars(def);
  const desc = (def.description || 'No description provided').replace(/"/g, '\\"');

  let fields = '';
  for (const envVar of envVars) {
    const fieldName = envVar.toLowerCase();
    fields += `    ${fieldName}: str = Field(description="Environment variable: ${envVar}")\n`;
  }

  const inputClass = envVars.length > 0
    ? `\nclass ${className}Input(BaseModel):\n    """Input schema for ${className}."""\n${fields}\n`
    : '';

  const argsSchema = envVars.length > 0
    ? `    args_schema: Type[BaseModel] = ${className}Input\n`
    : '';

  return `"""
${className} — Generated by effector compile --target langchain
Source: effector.toml + SKILL.md
"""

from langchain.tools import BaseTool
from pydantic import BaseModel, Field
from typing import Type, Optional

${inputClass}
class ${className}Tool(BaseTool):
    """${desc}"""
    name: str = "${name}"
    description: str = "${desc}"
${argsSchema}
    def _run(self, **kwargs) -> str:
        \"\"\"Execute the skill. Override this method with actual implementation.\"\"\"
        # Instruction passthrough: return SKILL.md content for the LLM
        return """${(def.skillContent || '').replace(/"""/g, '\\"\\"\\"').slice(0, 2000)}"""

    async def _arun(self, **kwargs) -> str:
        return self._run(**kwargs)
`;
}

// ── Helpers ───────────────────────────────────────────────

function normalizeName(name) {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function toPascalCase(name) {
  return name
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function extractEnvVars(def) {
  const vars = new Set();
  if (def.permissions?.envRead) {
    for (const v of def.permissions.envRead) vars.add(v);
  }
  if (def.requires?.env) {
    for (const v of def.requires.env) {
      if (v && typeof v === 'string') vars.add(v);
    }
  }
  return [...vars];
}
